### ISSUE TITLE
Recreate index.html 

### ISSUE THREAD

**Issue by ianshulx** [ianshulx/Django-Projects-for-beginners#26]
# Project List Page Improvement

## Problem Statement

Our current Project List page is very simple and lacks a visually appealing design. We need to enhance this page to make it more user-friendly and aesthetically pleasing.

## Objective

The goal is to create a new Project List page with the following requirements:

1. **Single Page Implementation**: Everything should be on the same page to keep it simple and straightforward.
2. **Technologies**: The page should be developed using simple HTML, CSS, and JavaScript. This will ensure that new contributors can easily understand, modify, and improve the page in a short amount of time.
3. **Design**: I've added an image of the expected UI for the new Project List page. The current page is located [here](https://github.com/ianshulx/Django-Projects-for-beginners/blob/main/index.html). 
*Check current page* [preview](https://anshul.life/Django-Projects-for-beginners/)

## How to Contribute

If you’re interested in contributing to this project, please fork the repository, make your changes, and submit a pull request. Your contributions will be greatly appreciated!

### Expected UI Design

![Expected UI - Image 1](https://raw.githubusercontent.com/ianshulx/React-projects-for-beginners/main/temp/1.png)
![Expected UI - Image 2](https://raw.githubusercontent.com/ianshulx/React-projects-for-beginners/main/temp/2.png)

**Comment by georgioupanayiotis** [comment]
@ianshulx can you pease assign me this issue ?

**Comment by ianshulx** [comment]
@georgioupanayiotis, Okay I'm assigning you for this issue, Please follow the objective of this issue carefully.

**Comment by akshatazore** [comment]
@ianshulx I’ve noticed the open issue related to the UI. I believe I could contribute by helping to resolve this issue. may i work on it ?

**Comment by ianshulx** [comment]
okay i've assigned you for this issue @akshatazore

**Comment by ianshulx** [comment]
@akshatazore , Wow! This UI is absolutely stunning! 😍 Your contribution has really taken the design to the next level. Massive thanks for your hard work and dedication, it’s contributions like yours that make open-source so awesome! 🙌✨

**Comment by ianshulx** [comment]
@akshatazore, Overall UI is amazing but there is one issue occurs in the contributor list, names of all contributors is available in the repo but not on the page you created recently, like your's name, can you please check that also what's the issue there.

**Comment by akshatazore** [comment]
Thank You @ianshulx !!
